 # 프로그래밍 기초 (Numpy, Pandas, Matplotlib)

# Numpy
- Numpy의 container : array

In [1]:
import numpy as np

arr = np.array([1, 2 ,3])

print(arr) # 기본적으로 행을 반환함!

# 열로 반환하기 위해서는 전치 행렬로 사용한다.
arr = arr[:, None]
# 열을 모두 가져오고 행은 아무것도 가져오지 않는다.
print(arr)

[1 2 3]
[[1]
 [2]
 [3]]


## 1. Numpy로 연산하기

### (1) vector와 sclar 사이의 연산
- 벡터의 각 원소에 대해서 연산을 진행

In [2]:
x = np.array([1, 2, 3]) 
c = 5

print("더하기 : {}".format(x + c))
print("빼기 : {}".format(x - c))
print("곱하기 : {}".format(x * c))
print("나누기 : {}".format(x / c))

더하기 : [6 7 8]
빼기 : [-4 -3 -2]
곱하기 : [ 5 10 15]
나누기 : [0.2 0.4 0.6]


### (2) vector와 vector사이의 연산
- vector의 **같은 인덱스**끼리 연산이 진행된다.

In [3]:
y = np.array([1, 3, 5])
z = np.array([2, 9, 20])

# array의 인자는 하나이기 때문에 묶어서 넣어줘야함
# np.array(1, 2, 3, 4) 는 동작하지 않음

print("더하기 : {}".format(y + z))
print("빼기 : {}".format(y - z))
print("곱하기 : {}".format(y * z))
print("나누기 : {}".format(y / z))

더하기 : [ 3 12 25]
빼기 : [ -1  -6 -15]
곱하기 : [  2  27 100]
나누기 : [0.5        0.33333333 0.25      ]


## 2. array indexing, slicing, broadcasting
### (1) array indexing

- phython의 리스트와 유사하게 진행

In [4]:
w = np.array([[1, 2, 3, 4,],[5, 6, 7, 8],[9, 10 ,11 ,12]])
w[2, 1]

10

### (2) array slicing


- phython의 리스트와 유사하게 진행

In [5]:
w = np.array([[1, 2, 3, 4,],[5, 6, 7, 8],[9, 10 ,11 ,12]])
 # 2, 3 -> 행 : 인덱스 0~1 -> [0:2]
 # 6, 7 -> 열 : 인덱스 1~2 -> [1:3]

w[0:2, 1:3]

# [a:b]

# [:b] -> 처음부터 b까지
# [a:] -> a부터 끝까지
# [:] -> 처음부터 끝까지

array([[2, 3],
       [6, 7]])

### (3) array broadcasting

- numpy가 배열 연산을 진행하는 특수한 방법

#### 1) M x N 연산 M x 1
numpy는 M x 1를 복사하여 **각 엘리먼트끼리** 연산을 한다.
(배열 곱과 다른 연산)

#### 2) M x N 연산 1 x N
numpy는 1 x N을 복사하여 **각 엘리먼트끼리** 연산을 한다.
(배열 곱과 다른 연산)


#### 3) M x 1 연산 1 x N
numpy는 1 x N을 복사한다.

numpy는 M x 1을 복사한다.

결론적으로 M x N의 연산이 결과로 나온다.
(배열 곱과 다른 연산)

# Numpy와 선형대수
## 1. 여러가지 행렬 선언
### (1) 영벡터 (영행렬)
- 원소가 모두 0인 백터(행렬)

In [6]:
np.zeros((3, 3))

# np.zeros(dim)
# dim에는 값 혹은 튜플(,)을 입력해주어야 한다.

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### (2) 일벡터 (일행렬)
- 원소가 모두 1인 백터(행렬)

In [7]:
np.ones((2,3))

# np.ones(dim)
# dim에는 값 혹은 튜플(,)을 입력해주어야 한다.

array([[1., 1., 1.],
       [1., 1., 1.]])

### (3) 대각행렬 (diagonal matrix)
- main diagonal을 제외한 성분이 0인 행렬

In [8]:
np.diag((2,4))

# np.diag(dim)
# dim에는 값 혹은 튜플(,)을 입력해주어야 한다.

array([[2, 0],
       [0, 4]])

### (4) 항등행렬 (identity matrix)
- main diagonal이 1인 대각행렬

In [9]:
np.eye(2, dtype=int)


# np.eye(n, dtype) 
# dtype은 선택 사항 (다른 함후도 동일) defalt는 float임
# 항등행렬은 항상 n x n 이기 때문에 하나의 숫자만 입력해주면 된다
# dtype : int, float, anssigned int, complex ...

array([[1, 0],
       [0, 1]])

### (5) 행렬 곱 (dot product)
- 행렬간의 곱연산

In [10]:
mat_1 = np.array([[1,4],[2,3]])
mat_2 = np.array([[7,9],[0,6]])

mat_1.dot(mat_2)

mat_1 @ mat_2

# matrix.dot(matrix)
# matrix @ matrix

array([[ 7, 33],
       [14, 36]])

## 2. trace, diterminant, 역행렬 다루기
### (1) trace
- Main diagoal의 합

In [11]:
w = np.array([[1, 2, 3, 4,],[5, 6, 7, 8],[9, 10 ,11 ,12]])

w.trace()

np.eye(2, dtype=int).trace()
# 항등행렬의 경우 trace 연산을 해주면 main diagonal이 1이므러 차원을 알 수 있음

2

### (2) determinant (행렬식)
- 행렬을 대표하는 값들 중 하나
- 선형변환 과정에서 Vector의 Scalling 척도
###
- 정사각 행렬에 스칼라를 대응시키는 함수의 하나이다.
- 실수 정사각 행렬의 행렬식의 절댓값은 그 행렬이 나타내는 선형 변환이 초부피를 확대시키는 배수를 나타낸다.
- 행렬식의 부호는 방향 보존 여부를 나타낸다.
###
- 2 x 2 일 때 ad - bc
- determinant가 0이라는 의미는 full rank가 아니다.
- 즉, 선형 변환 과정에서 차원의 손실이 일어난다.

In [12]:
arr_3 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

np.linalg.det(arr_3)

-9.51619735392994e-16

### (3) inverse matrix (역행렬)
- 항렬 A에 대해 AB = BA = I를 만족하는 행렬 B = A^I

In [13]:
arr_4 = np.array([[1, 2],[4, 5]])

arr_4_inv = np.linalg.inv(arr_4)

arr_4 @ arr_4_inv
# 위 연산이 1일 때 올바른 역행렬을 구한 것임

array([[1.00000000e+00, 0.00000000e+00],
       [2.22044605e-16, 1.00000000e+00]])

### (4) eigenvalue, eigenvector (고유값과 고유 벡터)
- 정방행렬(nxn) A에 대해 $Ax = \lambda x$를 만족하는 
- 상수 $\lambda$와 이에 대응하는 벡터 $x$
###
- 선형 변환을 진행하는 과정에서
- 같은 span에서 방향은 변하지않고 크기만 변할 때
- span ratio 비율을 고유값 람다,
- span 영역의 고유 벡터를 고유벡터라고 부른다.

In [14]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

eig_val, eig_vec = np.linalg.eig(A)

# return 값이 eigenvalue, eigenvector 두 가지임
# eigenvector는 column으로 봐야함

A_x = A @ eig_vec[:, 0] # Ax 한 column만 불러옴
lambda_x = eig_val[0] * eig_vec[:, 0] # (lambda)x 스칼라 *벡터

# A_x = lambda_x 이면 옳은 연산

# 실습
#### 문제 1. 어떤 벡터가 주어졌을 때 L2 norm을 구하는 함수 get_L2_norm()을 작성하세요.
###

#### 문제 2. 어떤 행렬이 singular matrix인지 확인하는 함수 is_singular()을 작성하세요.
###


# 필수 실습

In [3]:
import numpy as np

# 1. shape로 numpy 배열 모양 불러오기
# 머신 러닝에서 행렬의 차원 = shape
A = np.array([[1, 2, 3], [3, 4, 5]])
shape_of_A = A.shape

print(shape_of_A) # (2, 3) 출력

# 2. 3차원의 shape = (차원, 행, 열)
np.random.seed(42)

A = np.ones(shape=(2,1,3))
B = np.zeros(shape=(3,4,2))


print('-------------A의 출력-------------')
print(A)
print('-------------B의 출력-------------')
print(B)

# 3. 랜덤 배열 생성
# np.random.randn()을 사용하여 4 x 3 x 3 모양을 가진 배열을 만들어줍니다.
A = np.random.randn(4, 3, 3)


# np.random.normal()을 사용하여 평균 1.56, 표준편차 0.67의 5 x 6 모양을 가진 배열을 만들어줍니다.
B = np.random.normal(loc = 1.56, scale = 0.67, size=(5, 6))


# np.random.randint()을 사용하여 10부터 20까지 임의의 정수로 채워진 3 x 4 모양의 배열을 만들어줍니다.
C = np.random.randint(10, 21, size=(3,4))


print('-------------A의 출력-------------')
print(A)
print('-------------B의 출력-------------')
print(B)
print('-------------C의 출력-------------')
print(C)

# 4. 임의의 모양을 가진 numpy.ndarray 타입의 2차원 행렬 arr가 주어집니다. Numpy를 사용하여 (y1, x1)에서 (y2, x2)까지 구간에 해당하는 모든 요소의 값에 2를 곱하여 반환하는 함수를 구현하세요.
def solution(arr, y1, x1, y2, x2):
    arr[y1:y2+1, x1:x2+1] = arr[y1:y2+1, x1:x2+1] * 2
    answer = arr
    return answer

# 5. 


3
-------------A의 출력-------------
[[[1. 1. 1.]]

 [[1. 1. 1.]]]
-------------B의 출력-------------
[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]
-------------A의 출력-------------
[[[ 0.49671415 -0.1382643   0.64768854]
  [ 1.52302986 -0.23415337 -0.23413696]
  [ 1.57921282  0.76743473 -0.46947439]]

 [[ 0.54256004 -0.46341769 -0.46572975]
  [ 0.24196227 -1.91328024 -1.72491783]
  [-0.56228753 -1.01283112  0.31424733]]

 [[-0.90802408 -1.4123037   1.46564877]
  [-0.2257763   0.0675282  -1.42474819]
  [-0.54438272  0.11092259 -1.15099358]]

 [[ 0.37569802 -0.60063869 -0.29169375]
  [-0.60170661  1.85227818 -0.01349722]
  [-1.05771093  0.82254491 -1.22084365]]]
-------------B의 출력-------------
[[1.69993861 0.24702102 0.67011535 1.69189703 2.05477261 1.67481675]
 [1.48251565 1.35826052 0.56939027 1.07770438 1.25137202 2.26827189]
 [1.79022425 0.3787631  1.77713626 1.30199487 1.10646226 1.96982311]
 [2.25076968 2.1839